os: osx
osx_image: xcode10.1
branches:
  only:
    - master
script:
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework
  - xcodebuild -project TypedAssets.xcodeproj -scheme "TypedAssets" -destination "OS=12.0,name=iPhone XS" -configuration Release
